config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pictures#index'
  get '/license', to: 'pictures#license'
  
  namespace :admin do
    resources :users, :pictures
    root 'application#index'
  end

  resources :users, only: [:show, :edit, :update]
  resources :pictures do 
    member do
      put "like" => "pictures#upvote"
      delete "unlike" => "pictures#unvote"
      patch 'set_featured' => 'pictures#featured'
    end
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base	
	attr_accessor :tag_names
	
	belongs_to :user
	has_and_belongs_to_many :tags, uniq: true
	
	acts_as_votable
	mount_uploader :image_url, PhotoUploader
	
	validates :image_url, presence: true
	
	def tag_names=(names)
		@tag_names = names
		filtered = names.gsub(/[\,\.]/, "")
		filtered.downcase.split.each do |name|
			self.tags << Tag.find_or_initialize_by(name: name)
		end
	end
	
	def get_tags
		self.tags.map(&:name).join(', ')
	end
	
	def self.search(query)
		return "Sorry there's no pictures with those tags" unless query.present?
	  query = "#{query.strip.downcase}"
	  joins(:tags).where(tags: {name: query})
	end
	
	def self.get_random_picture
		if Picture.all.empty?
			return ""
		else
			Picture.where(featured: true).sample.image_url.url
		end
	end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	belongs_to :picture
end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_voter
	
	def self.search(query)
	  return none unless query.present?
	  query = "%#{query.strip}%"
	  where('first_name ILIKE ? OR username ILIKE ? or email ILIKE ?', query, query, query)
	end
	
	has_many :pictures
	mount_uploader :avatar, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
	def index
		if params[:query]
			@users = User.search(params[:query]).order("created_at DESC")
		end
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController	
	before_action :authenticate_user!
	
	def create
		@picture = Picture.find(params[:picture_id])
		@like = Like.find_or_create_by(user_id: current_user.id, picture: @picture)
				
		respond_to do |format|
			format.html {redirect_to root_path, flash[:notice] = "Like has been created!"}
			format.js
		end
	end
	
	def destroy
		@picture = Picture.find(params[:id])
		@like = @picture.likes.where(user: current_user)
		@like.destroy_all
		
		respond_to do |format|
			format.html {redirect_to root_path, flash[:notice] = "Like has been removed."}
			format.js
		end
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :upvote, :unvote]
	before_action :verify_admin, only: [:featured]
	

	def index
		if params[:query]
			@pictures = Picture.search(params[:query]).order(params[:sort]).where(featured: true).uniq
		else
			@pictures = Picture.order(params[:sort]).where(featured: true)
		end
		
		@picture = Picture.new
		
		gon.img = Picture.get_random_picture
	end

	def new
		@picture = Picture.new
	end
	
	def edit
		@picture = Picture.find(params[:id])
		@tags = @picture.get_tags
	end

	def create
		@picture = Picture.new(picture_params)
		@picture.user = current_user
		
		if params[:picture].blank?
			flash.now[:alert] = "Picture must be selected."
			render 'new'
			return
		end

		if @picture.save
			flash[:success] = "Photo has been saved."
			redirect_to user_path(current_user)
		else
			flash.now[:alert] = "Photo was not uploaded."
			render 'new'
		end
	end
	
	def update
		@picture = Picture.find(params[:id])
		if @picture.update(picture_params)
			flash[:notice] = "Picture has been updated successfully."
			redirect_to user_path(@picture.user)
		else
			flash.now[:alert] = "Picture was not updated."
			render 'edit'
		end
	end

	def destroy
		@picture = Picture.find(params[:id])
		@picture.destroy
		
		flash[:notice] = "Picture has been deleted."
		redirect_to user_path(@picture.user)
	end

	def license
		
	end
	
	def featured
		@picture = Picture.find(params[:id])
		@picture.featured = true
		@picture.save
		
		flash[:notice] = "Picture has been set to featured."
		redirect_to root_path
	end
	
	def upvote
		@picture = Picture.find(params[:id])
		@picture.liked_by(current_user)
		
		respond_to do |format|
			format.html {redirect_to root_path}
			format.js
		end
	end
	
	def unvote
		@picture = Picture.find(params[:id])
		@picture.unliked_by(current_user)
		
		respond_to do |format|
			format.html {redirect_to root_path}
			format.js
		end
	end

	private

	def picture_params
		params.require(:picture).permit(:image_url, :user_id, :tag_names)
	end
	
	def verify_admin
		unless current_user.admin?
			flash[:alert] = "Sorry only an admin can perform this feature"
			redirect_to root_path
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update]
	
	def show
		@pictures = @user.pictures.order(params[:sort])
	end
	
	def edit
	end
	
	def update
		if @user.update(user_params)
			flash[:notice] = "User has been updated."
			redirect_to user_path(@user)
		else
			flash.now[:alert] = "User has not been updated."
			render 'edit'
		end
	end
	
	private 
	
	def set_user
		@user = User.find(params[:id])
	end
	
	def user_params
		params.require(:user).permit(:username, :first_name, :user, 
		:last_name, :email, :location, :avatar, :about)
	end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def admins_only(&block)
		block.call if current_user.try(:admin?)
	end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/admin/application/index.html.erb
<div class='heading'>
	<h1>Welcome to the Admin tab!</h1>
	
	<p>Okay lets keep this simple. If you want to lookup a user you can search by email, name, or username.
		 From there you can delete an account or edit it. If you choose to edit it you can change their info or
		 delete pictures they uploaded if you'd like. You can also mark the pictures as featured if you would 
		 like them to be on the front page.
	</p>
	
	<%= simple_form_for admin_users_path, method: :get do |f| %>
		<%= f.text_field :query, name: 'query', placeholder: params[:query] %>
		
		<%= f.button :submit, "Search", name: nil %>
	<% end %>
	
	<div class='search_results'>
		<ul>
			<% if @users.present? %>
				<% @users.each do |user| %>
					<li class='userinfo'><%= link_to "#{user.first_name} - #{user.email}", user_path(user) %> 
						<%= link_to "Delete User", admin_user_path(user), class: "btn btn-danger" %>
					</li>
				<% end %>
			<% end %>
		</ul>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vastpic</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='headerbrand'>
	<div class='brand'>
		<%= link_to image_tag("http://goo.gl/hqYEue"), root_path %>
	</div>
</div>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Submit", new_picture_path(@picture) %></li>
        <li><%= link_to "License", license_path %></li>
        <% admins_only do %>
          <li><%= link_to "Admin", admin_root_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<% if user_signed_in? %>
      		<li><%= link_to image_tag(current_user.avatar.thumb.url), user_path(current_user), class: "thumb" %></li>
      		<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      	<% else %>
      		<li><%= link_to "Log in", new_user_session_path %></li>
      		<li><%= link_to "Sign up", new_user_registration_path %></li>
      	<% end %>
      </ul>
    </div>
  </div>
</nav>

<div class='container'>
   <% flash.each do |key, message| %>
     <div class='alert alert-<%= key %>'>
       <%= message %>
     </div>
   <% end %>
 </div>
	
<%= yield %>

</body>
</html>

app/views/pictures/_like.html.erb
<%= button_to like_picture_path(@picture), method: :put, remote: true, class: "likethisphoto" do %>
	<span class='likescount'><%= @picture.get_likes.count %></span>
	<i class="fa fa-heart-o" aria-hidden="true"></i>
<% end %>

app/views/pictures/_picture.html.erb
<div class='imageauthor'>
	<%= image_tag picture.image_url.url, class: "fullimg" %>
	<ul class='aboutsection'>
		<li> Photo by <%= link_to "#{picture.user.first_name} #{picture.user.last_name}", 
			user_path(picture.user) %> / 
			
			<%= link_to picture.image_url.url do %>
				<i class="fa fa-download" aria-hidden="true"></i>
			<% end %>
			
			<% if current_user.try(:admin?) || picture.user == current_user %> /
				<%= link_to picture_path(picture), method: :delete, data: {confirm: "Are you sure you want to delete this photo?"} do %>
					<i class="fa fa-trash" aria-hidden="true"></i>
				<% end %>
				
				<%= link_to edit_picture_path(picture) do %> /
					<i class="fa fa-wrench" aria-hidden="true"></i>
				<% end %>
			<% end %>
			
			<% if picture.featured == false %>
				<% admins_only do %> /
					<%= link_to set_featured_picture_path(picture), method: :patch,
					data: { confirm: "Are you sure you want to make this photo featured?" } do %>
						<i class="fa fa-check" aria-hidden="true"></i>
					<% end %>
				<% end %>
			<% end %>
			
			<span class= "likefunction" id="picture_<%= picture.id %>">
				<% if user_signed_in? && current_user.voted_for?(picture) %>
					<%= button_to unlike_picture_path(picture), method: :delete, remote: true, class: "likethisphoto" do %>
						<span class='likescount'><%= picture.get_likes.count %></span>
						<i class="fa fa-heart-o" aria-hidden="true"></i>
					<% end %>
				<% else %>
					<%= button_to like_picture_path(picture), method: :put, remote: true, class: "likethisphoto" do %>
						<span class='likescount'><%= picture.get_likes.count %></span>
						<i class="fa fa-heart-o" aria-hidden="true"></i>
					<% end %>
				<% end %>
			</span>
			
		</li>
	</p>
</div>

app/views/pictures/_unlike.html.erb
<%= button_to unlike_picture_path(@picture), method: :delete, remote: true, class: "likethisphoto" do %>
	<span class='likescount'><%= @picture.get_likes.count %></span>
	<i class="fa fa-heart-o" aria-hidden="true"></i>
<% end %>

app/views/pictures/edit.html.erb
<div class='editpage'>
	<h1>Edit Picture </h1>

	<%= image_tag @picture.image_url.url %>
	
	<%= simple_form_for @picture do |f| %>
		<%= f.input :tag_names, input_html: { value: @tags } %>
		
		<%= f.button :submit %>
	<% end %>
	
</div>

app/views/pictures/index.html.erb
<div class='main-content'>
<h2 class='greeting'>Free hi-res stock images for both personal & commercial use.</h2>
	
<ul class='optionsnavi'>
	<li class='dropdown'>
		<button class='dropbtn'>
			Sort By <i class="fa fa-sort-desc" aria-hidden="true"></i>
		</button>
			<div id='myDropdown' class='dropdown-content'>
				<%= link_to "Oldest", :sort => "created_at asc" %>
				<%= link_to "Latest", :sort => "created_at desc" %>
			</div>
	</li>
	<li class='sizetoggle'>
		<button type='button' class='single-img'>
			<i class="fa fa-bars fa-2x active" aria-hidden="true"></i>
		</button>
		<button type='button' class='multi-img'>
			<i class="fa fa-th-large fa-2x inactive" aria-hidden="true"></i>
		</button>
	</li>
</ul>

<div class='searchbar'>
	<%= form_tag root_path, method: :get, class: "tagsearch" do %>
		<%= text_field_tag :query, params[:query], placeholder: "Vintage, Mountain, Water, etc" %>
		
		<%= submit_tag "Search", name: nil, class: "btn btn-default" %>
	<% end %>
</div>
	
<div class='photo_section single'>
	<% @pictures.each do |picture| %>
		<%= render partial: 'picture', locals: {picture: picture} %>
	<% end %>
</div>

app/views/pictures/new.html.erb
<div class='submit-brand'>
	<%= link_to image_tag("http://goo.gl/hqYEue"), root_path %>
	<p>
		Your photo will be published on our website as soon as our teams reviews it for submission.
		After uploading your photo will be licensed under Creative Commons License (Creative Commons Zero CCO 1.0).

		<br>
		<br>

		The photo must be your own original content.
	</p>
	
	<%= simple_form_for @picture do |f| %>
		<%= f.input :image_url, label: "Image", as: :file %>
		<%= f.input :user_id, as: :hidden %>
		<%= f.input :tag_names, placeholder: "Ex. Vintage, Art, Filter, etc" %>

		<%= f.button :submit, "Submit", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/pictures/unvote.js.erb
$('#picture_<%= @picture.id %>').html("<%= escape_javascript(render partial: 'like') %>");

app/views/pictures/upvote.js.erb
$('#picture_<%= @picture.id %>').html("<%= escape_javascript(render partial: 'unlike') %>");

app/views/users/_picture.html.erb
<div class='imageauthor'>
	<%= image_tag picture.image_url.url, class: "fullimg" %>
	<ul class='aboutsection'>
		<li> Photo by <%= link_to "#{picture.user.first_name} #{picture.user.last_name}", 
			user_path(picture.user) %> / 
			
			<%= link_to picture.image_url.url do %>
				<i class="fa fa-download" aria-hidden="true"></i>
			<% end %>
			
			<% if current_user.try(:admin?) || picture.user == current_user %> /
				<%= link_to picture_path(picture), method: :delete, data: {confirm: "Are you sure you want to delete this photo?"} do %>
					<i class="fa fa-trash" aria-hidden="true"></i>
				<% end %>
				
				<%= link_to edit_picture_path(picture) do %> /
					<i class="fa fa-wrench" aria-hidden="true"></i>
				<% end %>
			<% end %>
			
			<% if picture.featured == false %>
				<% admins_only do %> /
					<%= link_to set_featured_picture_path(picture), method: :patch,
					data: { confirm: "Are you sure you want to make this photo featured?" } do %>
						<i class="fa fa-check" aria-hidden="true"></i>
					<% end %>
				<% end %>
			<% end %>
			
			<span class= "likefunction" id="picture_<%= picture.id %>">
				<% if user_signed_in? && current_user.voted_for?(picture) %>
					<%= button_to unlike_picture_path(picture), method: :delete, remote: true, class: "likethisphoto" do %>
						<span class='likescount'><%= picture.get_likes.count %></span>
						<i class="fa fa-heart-o" aria-hidden="true"></i>
					<% end %>
				<% else %>
					<%= button_to like_picture_path(picture), method: :put, remote: true, class: "likethisphoto" do %>
						<span class='likescount'><%= picture.get_likes.count %></span>
						<i class="fa fa-heart-o" aria-hidden="true"></i>
					<% end %>
				<% end %>
			</span>
			
		</li>
	</p>
</div>

app/views/users/crop.html.erb
<div class='imgcrop'>
	<h1>Please crop your avatar</h1>
	<%= image_tag @user.avatar.url, id: 'cropbox' %>

	<%= simple_form_for @user, class: "cropform" do |f| %>
		<% %w[ x y w h].each do |attribute| %>
			<%= f.input "crop_#{attribute}", as: :hidden, id: 'attribute' %>
		<% end %>
		
		<%= f.button :submit %>
	<% end %>
</div>

app/views/users/edit.html.erb
<div class='edit_form'>
	<h1>Edit Profile</h1>
	
	<%= simple_form_for(@user) do |f| %>
		<%= f.input :username %>
		<%= f.input :first_name %>
		<%= f.input :last_name %>
		<%= f.input :location %>
		<%= f.input :email %>
		
		<%= f.input :avatar, as: :file %>
		<%= f.input :about %>
		
		<%= f.button :submit, "Update Account" %>
	<% end %>
</div>

app/views/users/show.html.erb
<div class='profile-header'>
	<ul>
		<li><%= image_tag @user.avatar.medium.url, class: "avatarimg" %>
		<li><%= "#{@user.first_name} #{@user.last_name}" %></li>
		<li><%= @user.location %></li>
		<li><%= @user.about %></li>
	</ul>
</div>

<ul class='optionsnavi'>
	<li class='sorttoggle'>
		<%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-primary" %>
	</li>
	<li class='dropdown'>
		<button class='dropbtn'>
			Sort By <i class="fa fa-sort-desc" aria-hidden="true"></i>
		</button>
		<div id='myDropdown' class='dropdown-content'>
			<%= link_to "Oldest", :sort => "created_at asc" %>
			<%= link_to "Latest", :sort => "created_at desc" %>
		</div>
	</li>
	<li class='sizetoggle'>
		<button type='button' class='single-img'>
			<i class="fa fa-bars fa-2x active" aria-hidden="true"></i>
		</button>
		<button type='button' class='multi-img'>
			<i class="fa fa-th-large fa-2x inactive" aria-hidden="true"></i>
		</button>
	</li>
</ul>

<div class='photo_section single'>
	<% @pictures.each do |picture| %>
		<%= render partial: 'picture', locals: {picture: picture} %>
	<% end %>
</div>